"""initial

Revision ID: a602463f1062
Revises:
Create Date: 2024-11-24 12:54:30.234832

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a602463f1062'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'board',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('link', sa.VARCHAR(length=8), nullable=False),
        sa.Column('name', sa.VARCHAR(length=50), nullable=False),
        sa.Column('description', sa.VARCHAR(length=2000), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('link'),
    )
    op.create_table(
        'thread',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('number', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('title', sa.VARCHAR(length=200), nullable=False),
        sa.Column('text', sa.VARCHAR(length=15000), nullable=False),
        sa.Column('likes_count', sa.INTEGER(), nullable=False),
        sa.Column('dislikes_count', sa.INTEGER(), nullable=False),
        sa.Column('posters_count', sa.INTEGER(), nullable=False),
        sa.Column('posts_count', sa.INTEGER(), nullable=False),
        sa.Column('files_count', sa.INTEGER(), nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('number'),
    )
    op.create_table(
        'user',
        sa.PrimaryKeyConstraint('id'),
        sa.Column('email', sa.VARCHAR(length=50), nullable=True),
        sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('ip_address'),
    )
    op.create_table(
        'post',
        sa.PrimaryKeyConstraint('id'),
        sa.Column('number', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('author', sa.VARCHAR(length=50), nullable=False),
        sa.Column('text', sa.VARCHAR(length=15000), nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author'],
            ['user.ip_address'],
        ),
        sa.UniqueConstraint('number'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('thread')
    op.drop_table('board')
    # ### end Alembic commands ###
