"""add board id to thread

Revision ID: c35b9d99d81a
Revises: a602463f1062
Create Date: 2024-11-26 08:33:50.287020

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c35b9d99d81a'
down_revision: Union[str, None] = 'a602463f1062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('board_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'thread', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_column('thread', 'board_id')
    # ### end Alembic commands ###
